version: '3.1'

services:
  db:
    image: mongo
    restart: always
    networks:
      - node_billing_app
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./.docker/volumes/db:/data/db
  app:
    depends_on:
      - db
    image: ${DC_APP_IMAGE}
    restart: always
    ports:
      - ${DC_APP_PORT}:${APP_PORT}
    networks:
      - node_billing_app
    env_file:
      - ./.env
    links:
      - db:db
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app/
      - node_billing_app-node_modules:/usr/app/node_modules
    working_dir: /usr/app/
    command: "npm start-app"
networks:
  node_billing_app:
    driver: bridge
volumes:
  node_billing_app-node_modules:
